environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "7"
    - nodejs_version: "6"
    - nodejs_version: "4"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - npm test

build: off

cache:
  - node_modules
  - packages/*/node_modules
